### ISSUE TITLE
Error message when updating

### ISSUE THREAD

**Issue by stnk8** [klieret/anki-merge-notes#7] opened 2019-08-19 16:07 UTC
I've tried multiple things and cannot get this addon to work, but would love it because I have a project that needs exactly what this does.  This is the error I'm getting (the u'expression' field is the field I'm trying to use to find duplicates):

```
Traceback (most recent call last):
  File "/Users/meghanwhite/Library/Application Support/Anki2/addons/merge_notes_files/merge_notes.py", line 129, in loop
    expr = note[self.match_field]
  File "anki/notes.pyc", line 98, in __getitem__
  File "anki/notes.pyc", line 95, in _fieldOrd
KeyError: u'Expression'
```

**Comment by klieret** [comment] 2019-08-26 11:40
Hi, 

thank you for your interest in the addon, sorry for being slow with replying, I was on vacation.

This really sounds like you don't have a field called ``Expression`` and you write that your field is called ``expression`` (lower case). 

This can be changed in the config, did you try that?

Cheers,
Kilian

**Comment by stnk8** [comment] 2019-08-26 11:56
I was trying to merge Cloze notes and I initially wrote that the field I want to use is "Text" but that wasn't working so I changed it to "Expression" and that wasn't working either.  Both times the add-on and field capitalization was identical. Should I have written it lower case in the add-on?

**Comment by klieret** [comment] 2019-08-26 12:17
> Should I have written it lower case in the add-on? 

No, it should be exactly identical.

But are you sure that all notes that are tagged with either ``MERGE_FROM`` or ``MERGE_TO`` do indeed have this field? Perhaps you mixed up some notes of another type which do not have this field together with the others?

If this doesn't solve it, I might add some more debugging code that will print out the note where it fails, but this error really seems to be due to the field ``Expression`` not being found, so I'm pretty sure this is not a bug.

**Comment by klieret** [comment] 2019-08-26 12:23
Ah, but I never actually tried Cloze notes, but would be surprised if they work differently from normal notes. 

One more thing, just to make sure: As far as I understand it, if you have multiple cloze deletions for one note, several **cards** will created for the **same note**. This addon merges notes (which carry the content), not cards (which represent Question-Answer pairs made from a note). But you probably are aware of this.

**Comment by stnk8** [comment] 2019-08-26 12:34
I had the MERGE_FROM and MERGE_TO tags correct, all of both decks were the exact same note type (a cloze note with about 6 additional fields).  I ended up getting a different combine duplicates add-on to work, but it is not near as nice as yours and I definitely see the utility of yours.  If there's something I can do to help you debug, let me know. I'll try it once more to confirm I had everything correct

**Comment by klieret** [comment] 2019-08-26 12:40
Right, I see (I was just checking to exclude some of the more obvious kinds of fails). This addon started as a quick & dirty one-time thing, but I plan to brush it up in the future, since there seems to be some interest.

Let me add some snippet later that will print the exact note where it fails, perhaps this will help to find out what went wrong.

**Comment by stnk8** [comment] 2019-08-26 12:43
I just tried this again and it worked. Not sure what I was doing wrong.  This time I had the field set as "Text" and it seemed to have merged appropriately.  I deleted the original add-on and redownloaded so I'm not sure if that had anything to do with it.

**Comment by klieret** [comment] 2019-08-26 12:45
Thanks for testing this again!

There were some bugs that I had fixed around 2 weeks ago, but it didn't quite sound like any of the previous issues, so I'm not sure what might have caused it.

Anyway, I'm happy that it works :)

I will close this issue, but feel free to open a new one if other problems arise.

**Closed as completed by klieret** 2019-08-26 12:45 UTC
Labels: question
